# Generated by Django 4.1.7 on 2024-07-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('tables_of_2', models.IntegerField(default=0)),
                ('tables_of_4', models.IntegerField(default=0)),
                ('tables_of_6', models.IntegerField(default=0)),
                ('waiting_seats', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_mobile', models.CharField(max_length=15)),
                ('num_people', models.IntegerField()),
                ('reservation_time', models.DateTimeField()),
                ('table_type', models.IntegerField()),
                ('table_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.restaurant')),
            ],
        ),
    ]
