# Generated by Django 4.1.7 on 2024-07-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_type',
            field=models.IntegerField(choices=[(2, 'Table of 2'), (4, 'Table of 4'), (6, 'Table of 6')], default=2),
        ),
    ]
