# Generated by Django 4.1.7 on 2024-07-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_alter_reservation_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
